language: java
before_install:
  - sudo apt-get update
  - sudo apt-get install libc6-dev-i386
  - sudo apt-get install lib32ncurses5-dev
  - sudo apt-get install libx11-dev
  - sudo apt-get install g++-multilib
  - sudo apt-get install lib32z1-dev
  - wget http://dl.google.com/android/android-sdk_r22.6.2-linux.tgz
  - tar xf android-sdk_r22.6.2-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo "y" | android update sdk --filter tools,platform-tools,build-tools-19.0.3,android-16 --no-ui --no-https -a
install:
  - gem install --version 0.8.9 faraday
  - gem install travis-artifacts
script: 
  - mvn clean install -DTRAVIS=true
env:
  global:
    - "ARTIFACTS_AWS_REGION=us-east-1"
    - "ARTIFACTS_S3_BUCKET=travis-nightly"
    - secure: "MdfBKZzT5ojYO1vbV58GsCrmWHLYuQsJ3tXn1hAJ2boVy4UymXfpCNjlRsHG\nexupOKzQnmLZaeVQK5kNWkuqdzZFh0v0u8536n6mQ42bj7e7CvG5yrpJ5ryL\n2TzSreGazuQgFFfaGFX66KRdJ+7gvrA+DHpY8LzLXpnRBbNYz3Y="
    - secure: "Tuw1fHhLSdgTXU89+J0dXfVNvlU7nfFkE2ejmf2D3KVWhKxU3Bl0ggxz/R4u\ngtSiSpFr1ZAYlAWaWc2RKBobviIZdZcFhc7ydvx4cYo/2IIp1G6K82yIy3IW\ndjwjlXg18IX6y96uaS79Mpp3c0YZVFMCMeonWO8jk8eW6KB5VHU="
